version: '3.7'

services:
  priorizador:
      build:
        context: ./
        args:
          REACT_APP_API_URL: ${REACT_APP_API_URL}
          REACT_APP_DASH_URL: ${REACT_APP_DASH_URL}
      image: priorizador
      ports:
        - '8080:8080'
      networks:
        network:
          aliases:
            - priorizador
      volumes:
        - ./nginx_config/priorizador.conf:/etc/nginx/conf.d/priorizador.conf
        - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
      restart: 'always'

networks:
  network:
