version: '3.7'

services:
  flask-api:
    build: ./flask_api
    image: priorizador-api
    networks:
      network:
        aliases:
          - python-svc
    restart: 'always'
    volumes:
      - ./flask_api/geojson_data/:/home/geojson_data
    environment:
      - TEKOPORA
      - TECHO
      - ALMUERZO
      - FUNDACION
      - KOBO_API_TOKEN
      - CESTAS
      - ANDE_QUERY

  redis:
    image: redis

  celery-worker:
    build:
      context: ./visualizations_dash
      dockerfile: Dockerfile.Celery
    image: celery-worker
    entrypoint: celery
    command: -A dash_main.celery worker --loglevel=info
    links:
      - redis
    depends_on:
      - redis
    environment:
      - REDIS_SERVER

  celery-beat:
    build:
      context: ./visualizations_dash
      dockerfile: Dockerfile.Celery
    image: celery-beat
    entrypoint: celery
    command: -A dash_main.celery beat --loglevel=info
    links:
      - celery-worker
      - redis
    depends_on:
      - celery-worker
      - redis
    environment:
      - REDIS_SERVER

  dash:
    build: ./visualizations_dash
    image: dash
    ports:
      - '8050:8050'
    network_mode: host
    environment:
      - REACT_APP_API_URL
      - DASH_DEBUG_MODE
      - REDIS_SERVER

  priorizador:
    build:
      context: ./
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
        REACT_APP_DASH_URL: ${REACT_APP_DASH_URL}
    image: priorizador
    ports:
      - '8080:8080'
    networks:
      network:
        aliases:
          - priorizador
    volumes:
      - ./nginx_config/priorizador.conf:/etc/nginx/conf.d/priorizador.conf
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
    restart: 'always'

networks:
  network:
